name: GitHub Notification

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  notify:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Execute notification job
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: npx tsx src/index.ts
